sudo: false
language: python
python:
  - 3.4
install:
  - pip install -U pip
  - pip install -r docs/requirements-base.txt
script:
  - cd test
  - python -m coverage run --source ../src --omit */src/build.py runall.py
after_success:
  - bash <(curl -s https://codecov.io/bash)
